#!/usr/bin/env python3
"""build-team-logos.py — generate src/data/teamLogos.ts from ESPN team logos.

Matches the team names/abbreviations the predictor APIs actually use against
ESPN's team directory and writes a static {team -> logo URL} map per sport.
ESPN logo URLs are hotlinked at runtime; the <TeamLogo> component falls back
to the initial-letter avatar when a team has no mapped logo.

Regenerate with:  python3 scripts/build-team-logos.py
"""

from __future__ import annotations

import datetime
import json
import sys
import urllib.request

NFL_API = "https://nfl-predictor.proudbay-f56b8dfa.eastus2.azurecontainerapps.io"
CFB_API = "https://cfb-predictor.proudbay-f56b8dfa.eastus2.azurecontainerapps.io"
ESPN_NFL_TEAMS = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams?limit=32"
ESPN_CFB_TEAMS = "https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=900"

# App abbreviation -> ESPN abbreviation for the odd ones out.
# (App uses nfl_data_py abbreviations; OAK is a known stale duplicate of LV.)
NFL_ABBR_ALIASES = {"LA": "LAR", "WAS": "WSH", "OAK": "LV"}


def get_json(url: str):
    req = urllib.request.Request(
        url,
        # NOTE: ESPN's API currently 403s browser-like user agents from some
        # networks; a curl-style UA is accepted.
        headers={"User-Agent": "curl/8.5.0"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def espn_teams(url: str) -> list[dict]:
    data = get_json(url)
    return [t["team"] for t in data["sports"][0]["leagues"][0]["teams"]]


def logo_of(team: dict) -> str | None:
    logos = team.get("logos") or []
    return logos[0]["href"] if logos else None


def build_nfl_map() -> dict[str, str]:
    espn = {t["abbreviation"]: logo_of(t) for t in espn_teams(ESPN_NFL_TEAMS)}
    data = get_json(f"{NFL_API}/api/power-rankings?season=2026")
    rankings = data.get("rankings", data)
    app_abbrs = sorted({t["team"].strip() for t in rankings})
    mapping: dict[str, str] = {}
    missing: list[str] = []
    for abbr in app_abbrs:
        espn_abbr = NFL_ABBR_ALIASES.get(abbr, abbr)
        url = espn.get(espn_abbr)
        if url:
            mapping[abbr] = url
        else:
            missing.append(abbr)
    return mapping, missing


def cfb_location(team: dict) -> str:
    """ESPN displayName minus the mascot nickname, e.g. 'Ohio State Buckeyes' -> 'Ohio State'."""
    disp, nick = team["displayName"], team.get("name", "")
    if nick and disp.endswith(" " + nick):
        return disp[: -(len(nick) + 1)]
    return disp


def build_cfb_map() -> dict[str, str]:
    loc_to_logo: dict[str, str] = {}
    for t in espn_teams(ESPN_CFB_TEAMS):
        url = logo_of(t)
        if url:
            loc_to_logo.setdefault(cfb_location(t), url)
    lower = {k.lower(): v for k, v in loc_to_logo.items()}

    data = get_json(f"{CFB_API}/api/power-rankings?season=2026")
    rankings = data.get("rankings", data)
    names = {t["team"].strip() for t in rankings}
    games = get_json(f"{CFB_API}/api/games?season=2026&week=4")
    games = games if isinstance(games, list) else games.get("games", [])
    for g in games:
        names.add(g["home_team"].strip())
        names.add(g["away_team"].strip())

    mapping: dict[str, str] = {}
    missing: list[str] = []
    for name in sorted(names):
        url = loc_to_logo.get(name) or lower.get(name.lower())
        if url:
            mapping[name] = url
        else:
            missing.append(name)
    return mapping, missing


def write_ts(nfl: dict[str, str], cfb: dict[str, str], out_path: str) -> None:
    today = datetime.date.today().isoformat()
    lines = [
        "// AUTO-GENERATED by scripts/build-team-logos.py — do not edit by hand.",
        f"// Generated {today}. Sources: ESPN team APIs (logo art), predictor",
        "// power-rankings/games endpoints (team names). Re-run the script to refresh.",
        'import type { Sport } from "../types";',
        "",
        "export const NFL_LOGOS: Record<string, string> = {",
    ]
    lines += [f'  "{k}": "{v}",' for k, v in sorted(nfl.items())]
    lines += [
        "};",
        "",
        "export const CFB_LOGOS: Record<string, string> = {",
    ]
    lines += [f'  "{k}": "{v}",' for k, v in sorted(cfb.items())]
    lines += [
        "};",
        "",
        "/** Lowercase index so lookups tolerate casing drift in API team names. */",
        "function ciIndex(map: Record<string, string>): Record<string, string> {",
        "  const idx: Record<string, string> = {};",
        "  for (const [k, v] of Object.entries(map)) idx[k.toLowerCase()] = v;",
        "  return idx;",
        "}",
        "",
        "const NFL_LOGOS_CI = ciIndex(NFL_LOGOS);",
        "const CFB_LOGOS_CI = ciIndex(CFB_LOGOS);",
        "",
        "/** ESPN logo URL for a team, or undefined when the team has no mapped logo. */",
        "export function teamLogoUrl(sport: Sport, team: string): string | undefined {",
        '  const [map, ci] = sport === "nfl" ? [NFL_LOGOS, NFL_LOGOS_CI] : [CFB_LOGOS, CFB_LOGOS_CI];',
        "  const key = team.trim();",
        "  return map[key] ?? ci[key.toLowerCase()];",
        "}",
        "",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main() -> int:
    nfl_map, nfl_missing = build_nfl_map()
    cfb_map, cfb_missing = build_cfb_map()
    print(f"NFL: {len(nfl_map)} mapped, {len(nfl_missing)} missing: {nfl_missing}")
    print(f"CFB: {len(cfb_map)} mapped, {len(cfb_missing)} missing: {cfb_missing}")
    write_ts(nfl_map, cfb_map, "src/data/teamLogos.ts")
    print("wrote src/data/teamLogos.ts")
    if nfl_missing or cfb_missing:
        print("WARNING: some teams have no logo; they will use the initial avatar.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
